# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "patreon"
    name       = "Patreon"
    url        = "https://patreon.com/rito_3d"

    [social.params]
        icon = "brand-patreon"

[[social]]
    identifier = "x"
    name       = "X"
    url        = "https://x.com/rito_3d"

    [social.params]
        icon = "brand-x"
