# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon        = "img/avatar.png"

# Accepted values: "default", "lastmod"
# default = see https://gohugo.io/quick-reference/glossary/#default-sort-order
# lastmod = sort by last modified date, in descending order
SortBy              = "default"

[footer]
    since      = 2020
    customText = ""

[dateFormat]
    published   = ":date_full"
    lastUpdated = ":date_full"

[sidebar]
    emoji    = "🦝"
    handle = "@Rito_3D"
    subtitle = "@Rito_3D"
    avatar   = "img/avatar.png"
    description = "3D Technical Artist specializing in Warudo and Vtubing."
    contactEmail = "foo@gmail.com"
    contactUsername = "ohnyoo.scbp"

[avatar]
    width = 2048

[article]
    headingAnchor = false
    math          = false
    readingTime   = false

    [article.list]
		showTags = false
        showCategories = false
    [article.license]
        enabled = false
        default = "Licensed under CC BY-NC-SA 4.0"

[widgets]
    homepage = [
        { type = "search" },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[opengraph.twitter]
    site = ""
    card = "summary_large_image"

[colorScheme]
    toggle  = false
    default = "dark"

## Comments
[comments]
    enabled  = false
    provider = "disqus"

    # See all the available configurations at https://github.com/CaiJimmy/hugo-theme-stack/blob/master/config/_default/params.toml
    # Copy the configurations you need from there and paste it here.

[prices]
    scene = 200
    environment = 400
    prop = 50
    character = 50
    vrchat = 50
    shorts = 20
    videos = 100
    modularavatar = 80
    consultations = 0
